services:
  - type: web
    name: linkedin-scraper
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_API_URL
        value: ""
    plan: free