services:
  - type: web
    name: linkedin-scraper
    runtime: node
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_API_URL
        value: ""
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
    plan: free